name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1,16 * *'

jobs:
#   tests:
#     name: PHP ${{ matrix.php }}, SF ${{ matrix.symfony }} - ${{ matrix.deps }}
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         php: [ 8.2, 8.3, 8.4 ]
#         deps: [ highest ]
#         symfony: [7.4.*, 7.0.* ]
#         include:
#           - php: 8.2
#             deps: lowest
#             symfony: '*'
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup PHP
#         uses: shivammathur/setup-php@v2
#         with:
#           php-version: ${{ matrix.php }}
#           coverage: none
#           tools: flex

#       - name: Install dependencies
#         uses: ramsey/composer-install@v3
#         with:
#           dependency-versions: ${{ matrix.deps }}
#           composer-options: --prefer-dist
#         env:
#           SYMFONY_REQUIRE: ${{ matrix.symfony }}

#       - name: Test
#         run: vendor/bin/phpunit

  php-stan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Install dependencies
        uses: ramsey/composer-install@v3

      - name: PHPStan
        run: vendor/bin/phpstan analyse

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install dependencies
        uses: ramsey/composer-install@v3

      - name: PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff